env:
  node: true
  es6: true

globals:
  every: true
  after: true
  constantly: true

ignorePatterns: ["generated/"]

rules:
  camelcase: [2, {properties: "always"}]
  comma-dangle: 0
  comma-spacing: [2, {before: false, after: true}]
  comma-style: [2, "last"]
  handle-callback-err: [2, "^.*(e|E)rr" ]
  indent: ["error", 2, {"SwitchCase": 1}]
  key-spacing: [2, { beforeColon: false, afterColon: true }]
  max-depth: [1, 3]
  max-len: ["error", {"code": 120, "tabWidth": 2, "ignoreComments": true}]
  max-nested-callbacks: [1, 7]
  no-cond-assign: 2
  no-constant-condition: 2
  no-dupe-args: 2
  no-dupe-keys: 2
  no-else-return: 2
  no-empty: 2
  no-lonely-if: 2
  no-multiple-empty-lines: 2
  no-nested-ternary: 2
  no-self-compare: 2
  no-sync: 1
  no-throw-literal: 2
  no-underscore-dangle: 0
  quote-props: [2, "as-needed"]
  quotes: [2, "single", {"avoidEscape": true}]
  radix: 2
  semi-spacing: [2, {before: false, after: true}]
  semi: [2, "always"]
  keyword-spacing: [2, {before: true, after: true}]
  space-before-blocks: [2, "always"]
  space-before-function-paren: [1, "never"]
  space-in-parens: [2, "never"]
  spaced-comment: [1, "always"]
  strict: [2, "global"]
  valid-jsdoc: 2
  yoda: [2, "never"]

extends: [prettier]

parserOptions:
  ecmaVersion: 2017
