env:
  node: true
  es6: true
globals:
  every: true
  after: true
  constantly: true
ignorePatterns: ['generated/', 'types/interfaces.d.ts']
rules:
  prettier/prettier: 'error'
extends: ['prettier']
plugins: ['prettier']
parserOptions:
  ecmaVersion: 2018
