instrumentation:
    root: .
    extensions:
        - .js
    default-excludes: false
    excludes: ['**/rosidl_parser/**', '**/src/**', '**/generated/**', '**/docs/**', '**/build/**', '**/scripts/**', '**/rosidl_gen/**', '**/node_modules/**']
