# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name:  ROS Rolling - Linux Build and Test

on: [push, pull_request, workflow_dispatch]
jobs:
  build:

    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        node-version: [10.X, 12.x, 14.X, 16.X, 17.X]

    steps:
    - name: Setup ROS2
      uses: ros-tooling/setup-ros@v0.2
      with:
        required-ros-distributions: rolling

    - name: Install test-msgs on Linux
      run: |
        sudo apt install ros-rolling-test-msgs

    - uses: actions/checkout@v2
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Run test suite on Linux
      run: |
        source /opt/ros/rolling/setup.bash
        npm i

    - name: Run test suite
      shell: bash
      run: |
        source /opt/ros/rolling/setup.bash
        node ./scripts/compile_tests.js
        source install/local_setup.bash
        node --expose-gc ./scripts/run_test.js
