# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ROS Humble - Linux Build and Test

on:
  push:
    branches: [ humble-hawksbill ]
  pull_request:
    branches: [ humble-hawksbill ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        node-version: [10.X, 12.x, 14.X, 16.X, 17.X]

    steps:
    - name: Setup ROS2
      uses: ros-tooling/setup-ros@v0.3
      with:
        required-ros-distributions: humble

    - name: Install test-msgs on Linux
      run: |
        sudo apt install ros-humble-test-msgs

    - uses: actions/checkout@v3

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build rclnodejs
      run: |
        source /opt/ros/humble/setup.bash
        npm i

    - name: Run test suite
      run: |
        source /opt/ros/humble/setup.bash
        npm test
