name: Windows Build and Test (Reusable)

on:
  workflow_call:
    inputs:
      trigger_type:
        description: 'Type of trigger (pr or push)'
        required: true
        type: string

jobs:
  build:
    runs-on: windows-2025
    strategy:
      fail-fast: false
      matrix:
        node-version: [24.X]
        ros_distribution:
          - humble
          - jazzy
          - kilted
          - rolling
    steps:
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Setup ROS2
      uses: ros-tooling/setup-ros@v0.7
      with:
        required-ros-distributions: ${{ matrix.ros_distribution }}

    - name: Prebuild - Setup VS Dev Environment
      uses: seanmiddleditch/gha-setup-vsdevenv@v4

    - uses: actions/checkout@v6

    - name: Build rclnodejs
      shell: cmd
      run: |
        call "c:\dev\${{ matrix.ros_distribution }}\ros2-windows\setup.bat"
        npm i

    - name: Test rclnodejs
      if: ${{ matrix.ros_distribution == 'jazzy' }}
      shell: cmd
      run: |
        call "c:\dev\${{ matrix.ros_distribution }}\ros2-windows\setup.bat"
        npm test
