name: Windows

on:
  push:
    branches:
      - develop
      - kilted
      - jazzy
      - humble-hawksbill
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/windows-build.yml
    with:
      trigger_type: "push"
    secrets: inherit

  jazzy-build-and-test:
    uses: ./.github/workflows/windows-jazzy-build-and-test.yml
    with:
      trigger_type: "push"
    secrets: inherit
